name: Release
on: push
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: "18.x"
      - name: Lint
        run: yarn lint
      - name: Code style
        run: yarn prettier --check .
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: "18.x"
      - name: Type check
        run: yarn ts
  release:
    name: Create GitHub release
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: "18.x"
          fetch-depth: 0
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # publish:
  #   name: Publish Electron app
  #   needs: release
  #   strategy:
  #     matrix:
  #       os: [macos-latest]
  #   runs-on: ${{ matrix.os }}
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: mskelton/setup-yarn@v1
  #       with:
  #         node-version: "18.x"
  #     - name: Update manifest version
  #       run:
  #         npm version --no-git-tag-version ${{ needs.release.outputs.version }}
  #     - name: Publish app
  #       run: yarn electron-forge publish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
