name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: mskelton/setup-pnpm@v1
        with:
          node-version: "18.x"
      - name: Publish Electron app
        run: pnpm electron-forge publish
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
